### ISSUE TITLE
transposematrix,java

### ISSUE THREAD

**Issue by ruchikayadav1408** [ruchikayadav1408/DSA-JAVA#1]
write a code in java using functions

**Comment by Parneet-Raghuvanshi** [comment]
Hi @ruchikayadav1408,
Can I really do this question?

**Comment by ruchikayadav1408** [comment]
> Hi @ruchikayadav1408, Can I really do this question?

yes ofcourse!!!

**Comment by Parneet-Raghuvanshi** [comment]
Thanks for accepting the PR really appreciated, (rip code) 👍🏻 , so this issue should be closed now, Right?
